
version: '3.8'

services:
  nginx:
    build: ./nginx
    image: nginx

    ports:
      - "80:80"  # Correctly exposes port 80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Correctly maps the nginx.conf file
    networks:
      - nginx-network

  python-app:
    build: 
      context: ./Python # Ensure you have a Dockerfile in the same directory
    container_name: python_app
    ports:
      - "8000:8000"  # This makes port 8000 available to other services in the network
    networks:
      - nginx-network

networks:
  nginx-network:
    driver: bridge  # This sets up a bridge network for the containers
